### ISSUE TITLE
Request to Add a License

### ISSUE THREAD

**Issue by lonesometraveler** [ltriant/atari2600#1]
Hello,

I've been exploring this project and noticed that it doesn't have a license. I kindly request that you consider adding an open-source license to the repository.

As I'm currently learning how Atari 2600 works, your project has been a valuable resource. I would like to experiment based on your work and, if possible, contribute to the project.

Thank you for your time and consideration.

**Comment by ltriant** [comment]
Hi @lonesometraveler !

Thanks for the interest. I've added a MIT License to the project.

Feel free to take whichever parts of this project are interesting to you :)

**Comment by lonesometraveler** [comment]
Hi @ltriant, 

Thank you so much for adding the MIT License to the project! I appreciate your openness and generosity.
